source 'http://rubygems.org'

gem 'rails', '3.0.6.rc2'

gem 'sqlite3'
gem 'warden'
gem 'devise'
gem 'paperclip'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'jquery-rails'
gem 'nifty-generators'
gem 'cancan'
gem 'meta_search'
gem 'will_paginate'
gem 'aws-s3'
#gem 'client_side_validations'